spring:
  application:
    name: multi-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/wangqiang766/config-report.git
          search-paths: '{application}'

server:
  port: 1300



